a = input ("Digite algo\n")
print("O tipo primitivo desse valor é", type(a))
print("Só tem espaços ? ", a.isspace())
print("São numeros ? ", a.isnumeric())
print("É alfabetico ? ", a.isalpha())
print("É alfanumerico ? ", a.isalnum())
print("Está em maiusculas ? ", a.isupper())
print("Está em minusculas ? ", a.islower())
print("Está capitalizada ? ", a.istitle())
